// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZQCfzw5Ll_l1vZG7n902YOIW1XDIJJY',
    appId: '1:1035833732716:web:dca449898f1105dc877249',
    messagingSenderId: '1035833732716',
    projectId: 'uc-math',
    authDomain: 'uc-math.firebaseapp.com',
    storageBucket: 'uc-math.appspot.com',
    measurementId: 'G-K19ZV5NTSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXS6zdMfhdyJw42p9_cwBhZajlaMSdkAU',
    appId: '1:1035833732716:android:1465ba52525baf32877249',
    messagingSenderId: '1035833732716',
    projectId: 'uc-math',
    storageBucket: 'uc-math.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6QvRhyfvcJDxRk0EMktuIY9JrhKyV94',
    appId: '1:1035833732716:ios:684a35ea3e1d6308877249',
    messagingSenderId: '1035833732716',
    projectId: 'uc-math',
    storageBucket: 'uc-math.appspot.com',
    iosBundleId: 'com.ucmaslab.ucMasApp',
  );
}
